In [52]:
import pandas as pd
import numpy as np

In [53]:
with open("./week1_assign.txt", "r") as file: 
    data = file.readlines()
    dum = []
    file_set = set()
    for row in data:
        dum.append(row.strip().split(";"))
        file_set.update(row.strip().split(";"))

df = pd.DataFrame(dum)

df.shape

(77185, 10)

In [54]:
ls_dum = []
for index, row in df.iterrows():
    dum = set(row.values)
    ls_dum.append(dum)
len(ls_dum)

77185

In [55]:
len(set(ls_dum))

TypeError: unhashable type: 'set'

In [ ]:
df

,0,1,2,3,4,5,6,7,8,9
0,Breakfast & Brunch,American (Traditional),Restaurants,None,None,None,None,None,None,None
1,Sandwiches,Restaurants,None,None,None,None,None,None,None,None
2,Local Services,IT Services & Computer Repair,None,None,None,None,None,None,None,None
3,Restaurants,Italian,None,None,None,None,None,None,None,None
4,Food,Coffee & Tea,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...
77180,Doctors,Cosmetic Surgeons,Beauty & Spas,Medical Spas,Skin Care,Health & Medical,None,None,None,None
77181,Fashion,Shopping,None,None,None,None,None,None,None,None
77182,Doctors,Health & Medical,Obstetricians & Gynecologists,None,None,None,None,None,None,None
77183,Food,Coffee & Tea,None,None,None,None,None,None,None,None
77184,Food,Health Markets,Grocery,Specialty Food,None,None,None,None,None,None

In [ ]:
# create blank list in the dict
unique_cat = {k: [] for k in file_set} 
for index, row in df.iterrows():
    dum = list(row.values)
    # remove all the items find in the dum list
    set_ = file_set.difference(dum)
    # for loop the dum list and append the key into each list and others not find in dum list will loop through set_ and insert null value
    for key in dum:
        if key != None:
            unique_cat[key].append(True)
        else: 
            break
    for key in set_:
        unique_cat[key].append(False)


unique_cat["Restaurants"]

[True,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 ...]

In [ ]:
final_df.columns

Index(['Session Photography', 'Gastropubs', 'Beverage Store',
       'Employment Agencies', 'Bartenders', 'Medical Centers', 'Walking Tours',
       'Lice Services', 'Plus Size Fashion', 'Fireworks',
       ...
       'Obstetricians & Gynecologists', 'Parking', 'Women's Clothing',
       'Drugstores', 'Appliances', 'Travel Services',
       'Ice Cream & Frozen Yogurt', 'Career Counseling', 'Arcades',
       'Comedy Clubs'],
      dtype='object', length=892)

In [ ]:
final_df = pd.DataFrame(unique_cat)

In [191]:
from mlxtend.frequent_patterns import apriori, association_rules

# Extracting the most frequest itemsets via Mlxtend.
# The length column has been added to increase ease of filtering.
frequent_itemsets = apriori(final_df, min_support=0.01, use_colnames=True)
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets["abs support"] = round(frequent_itemsets["support"] * df.shape[0]).astype(int)
# printing the frequent itemset
frequent_itemsets

,support,itemsets,length,abs support
0,0.044931,(Local Services),1,3468
1,0.119842,(Food),1,9250
2,0.030628,(Sandwiches),1,2364
3,0.085289,(Beauty & Spas),1,6583
4,0.010663,(General Dentistry),1,823
...,...,...,...,...
96,0.010598,"(Bars, Sports Bars, Nightlife)",3,818
97,0.011323,"(Bars, Pubs, Nightlife)",3,874
98,0.010028,"(Fast Food, Restaurants, Burgers)",3,774
99,0.014744,"(Fashion, Shopping, Women's Clothing)",3,1138
100,0.018540,"(Hotels & Travel, Event Planning & Services, H...",3,1431

In [192]:
## convert the forzenset into list
item_list  = []
abs_support_list = []
for index, row in frequent_itemsets.iterrows():
    item_list.append(list(row["itemsets"]))
    abs_support_list.append(row["abs support"])

In [193]:
result_string = str()
for n in range(len(item_list)):
    if len(item_list[n]) == 1:
        item_str = str()
        result_string = str(result_string) + f"{int(abs_support_list[n])}:{item_list[n][0]}\n"
result_string = result_string.strip()
result_string

"3468:Local Services\n9250:Food\n2364:Sandwiches\n6583:Beauty & Spas\n823:General Dentistry\n4328:Bars\n25071:Restaurants\n1150:Specialty Food\n1424:Grocery\n5121:Health & Medical\n5088:Nightlife\n848:Japanese\n2416:American (Traditional)\n818:Sports Bars\n1369:Breakfast & Brunch\n11233:Shopping\n1195:Dentists\n1002:Cafes\n1424:Real Estate\n874:Pubs\n2657:Pizza\n875:Financial Services\n798:Sushi Bars\n1848:Italian\n1593:American (New)\n2515:Mexican\n1497:Pets\n1442:Fitness & Instruction\n2851:Fast Food\n870:Pet Services\n1629:Chinese\n3078:Fashion\n1115:Bakeries\n3103:Active Life\n4785:Home Services\n1025:Professional Services\n1694:Doctors\n1667:Nail Salons\n2199:Coffee & Tea\n1774:Burgers\n1586:Home & Garden\n2091:Hair Salons\n1431:Hotels\n4208:Automotive\n2271:Arts & Entertainment\n2975:Event Planning & Services\n2495:Hotels & Travel\n1716:Auto Repair\n1138:Women's Clothing\n1018:Ice Cream & Frozen Yogurt"

In [194]:
with open('./week1_assign_results.txt', 'w') as f:
    f.writelines(result_string)

In [199]:
result_string = str()
for n in range(len(item_list)):
    item_str = str()
    if len(item_list[n]) == 1:
        item_str = f"{item_list[n][0]}"
    else:
        for m in range(len(item_list[n])):
            if m == 0:
                item_str = f"{item_list[n][m]}"
            else:
                item_str = f"{item_str};{item_list[n][m]}"
            # itme_str = str(item_list[n][0])
    result_string = str(result_string) + f"{int(abs_support_list[n])}:{item_str}\n"
result_string = result_string.strip()
result_string

"3468:Local Services\n9250:Food\n2364:Sandwiches\n6583:Beauty & Spas\n823:General Dentistry\n4328:Bars\n25071:Restaurants\n1150:Specialty Food\n1424:Grocery\n5121:Health & Medical\n5088:Nightlife\n848:Japanese\n2416:American (Traditional)\n818:Sports Bars\n1369:Breakfast & Brunch\n11233:Shopping\n1195:Dentists\n1002:Cafes\n1424:Real Estate\n874:Pubs\n2657:Pizza\n875:Financial Services\n798:Sushi Bars\n1848:Italian\n1593:American (New)\n2515:Mexican\n1497:Pets\n1442:Fitness & Instruction\n2851:Fast Food\n870:Pet Services\n1629:Chinese\n3078:Fashion\n1115:Bakeries\n3103:Active Life\n4785:Home Services\n1025:Professional Services\n1694:Doctors\n1667:Nail Salons\n2199:Coffee & Tea\n1774:Burgers\n1586:Home & Garden\n2091:Hair Salons\n1431:Hotels\n4208:Automotive\n2271:Arts & Entertainment\n2975:Event Planning & Services\n2495:Hotels & Travel\n1716:Auto Repair\n1138:Women's Clothing\n1018:Ice Cream & Frozen Yogurt\n2101:Food;Restaurants\n1150:Food;Specialty Food\n1424:Grocery;Food\n1115:Bakeries;Food\n2199:Food;Coffee & Tea\n1018:Ice Cream & Frozen Yogurt;Food\n2364:Sandwiches;Restaurants\n1667:Beauty & Spas;Nail Salons\n2091:Beauty & Spas;Hair Salons\n823:General Dentistry;Health & Medical\n823:General Dentistry;Dentists\n2423:Bars;Restaurants\n4328:Bars;Nightlife\n818:Bars;Sports Bars\n874:Bars;Pubs\n2533:Restaurants;Nightlife\n848:Japanese;Restaurants\n2416:American (Traditional);Restaurants\n1369:Breakfast & Brunch;Restaurants\n1002:Cafes;Restaurants\n2657:Pizza;Restaurants\n798:Restaurants;Sushi Bars\n1848:Italian;Restaurants\n1593:American (New);Restaurants\n2515:Mexican;Restaurants\n2851:Fast Food;Restaurants\n1629:Chinese;Restaurants\n1774:Restaurants;Burgers\n1195:Health & Medical;Dentists\n1694:Health & Medical;Doctors\n818:Sports Bars;Nightlife\n874:Pubs;Nightlife\n3078:Fashion;Shopping\n1586:Shopping;Home & Garden\n1138:Shopping;Women's Clothing\n1424:Real Estate;Home Services\n870:Pets;Pet Services\n1442:Active Life;Fitness & Instruction\n774:Fast Food;Burgers\n1138:Fashion;Women's Clothing\n1431:Event Planning & Services;Hotels\n1431:Hotels & Travel;Hotels\n1716:Automotive;Auto Repair\n1471:Hotels & Travel;Event Planning & Services\n823:General Dentistry;Health & Medical;Dentists\n2423:Bars;Restaurants;Nightlife\n818:Bars;Sports Bars;Nightlife\n874:Bars;Pubs;Nightlife\n774:Fast Food;Restaurants;Burgers\n1138:Fashion;Shopping;Women's Clothing\n1431:Hotels & Travel;Event Planning & Services;Hotels"

In [200]:
with open('./week1_assign_results_itemsets.txt', 'w') as f:
    f.writelines(result_string)