In [24]:
import pandas as pd
import numpy as np

In [34]:
with open("./week1_assign.txt", "r") as file: 
    data = file.readlines()
    dum = []
    for row in data:
        dum.append(row.strip().split(";"))

df = pd.DataFrame(dum)

,0,1,2,3,4,5,6,7,8,9
0,Breakfast & Brunch,American (Traditional),Restaurants,None,None,None,None,None,None,None
1,Sandwiches,Restaurants,None,None,None,None,None,None,None,None
2,Local Services,IT Services & Computer Repair,None,None,None,None,None,None,None,None
3,Restaurants,Italian,None,None,None,None,None,None,None,None
4,Food,Coffee & Tea,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...
77180,Doctors,Cosmetic Surgeons,Beauty & Spas,Medical Spas,Skin Care,Health & Medical,None,None,None,None
77181,Fashion,Shopping,None,None,None,None,None,None,None,None
77182,Doctors,Health & Medical,Obstetricians & Gynecologists,None,None,None,None,None,None,None
77183,Food,Coffee & Tea,None,None,None,None,None,None,None,None
77184,Food,Health Markets,Grocery,Specialty Food,None,None,None,None,None,None